style = "yas"
indent = 4
margin = 120
always_for_in = false
whitespace_ops_in_indices = true
whitespace_typedefs = true
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
always_use_return = false
