name = "AcuteML"
uuid = "6b84a0a3-a11a-41fa-a417-e600528de108"
authors = ["Amin Yahyaabadi"]
version = "0.2.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]
EzXML = "< 1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[targets]
test = ["Test","Suppressor"]
