name = "AcuteML"
uuid = "6b84a0a3-a11a-41fa-a417-e600528de108"
authors = ["Amin Yahyaabadi"]
version = "0.3.1"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
EzXML = "< 1.0"
PrettyTables = "0.8"
Tables = "0.2"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[targets]
test = ["Test", "Suppressor", "DataFrames", "Dates", "EzXML"]
