name = "AcuteML"
uuid = "6b84a0a3-a11a-41fa-a417-e600528de108"
authors = ["Amin Yahyaabadi"]
version = "0.10.2"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
TypeTransform = "0fb2cfb0-ef68-4639-af2f-cb92dac991ae"

[compat]
EzXML = "1.0, 1.1"
PrettyTables = "0.8, 0.9"
Reexport = "^0.2.0"
Tables = "0.2, 1.0"
TypeTransform = "0.1.3"
Tricks = "0.1.3"
julia = "1.2"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
MusicXML = "521615e9-e573-4eb2-bc7e-702d55c0bb95"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor", "DataFrames", "Dates", "EzXML", "MusicXML"]
